# Generated by Django 3.2.4 on 2021-06-15 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pretencao_salarial', models.CharField(max_length=25)),
                ('escolaridade', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=30)),
                ('experiencia', models.CharField(max_length=400)),
                ('aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidato.aplicacao')),
            ],
        ),
    ]
