# Generated by Django 3.2.4 on 2021-06-15 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidato', '0001_initial'),
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacao',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aplicacao',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.vaga'),
        ),
    ]
