# Generated by Django 3.2.4 on 2021-06-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0003_aplicacao_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacao',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
